In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Project_2/TATA-IPL-2025-Auction-List.csv')

In [ ]:
df.head()

,List Sr.No.,Set No.,2025 Set,First Name,Surname,Country,State Association,DOB,Age,Specialism,...,Bowling Skills,Test caps,ODI caps,T20 caps,IPL caps,Previous IPLTeam(s),2024 Team,2024 IPL,C/U/A,Reserve Price Rs Lakh
0,1,1,M1,Jos,Buttler,England,NaN,08-09-1990,34,WICKETKEEPER,...,RIGHT ARM Off Spin,57.0,181.0,124.0,107.0,"MI,RR",RR,11.0,Capped,200
1,2,1,M1,Shreyas,Iyer,India,MCA,06-12-1994,30,BATTER,...,RIGHT ARM Off Spin,14.0,62.0,51.0,116.0,"DC,KKR",KKR,15.0,Capped,200
2,3,1,M1,Rishabh,Pant,India,DDCA,04-10-1997,27,BATTER,...,RIGHT ARM Off Spin,37.0,31.0,76.0,111.0,DC,DC,13.0,Capped,200
3,4,1,M1,Kagiso,Rabada,South Africa,NaN,25-05-1995,29,BOWLER,...,RIGHT ARM Fast,66.0,101.0,65.0,80.0,"DC,PBKS",PBKS,11.0,Capped,200
4,5,1,M1,Arshdeep,Singh,India,PCA,05-02-1999,26,BOWLER,...,LEFT ARM Fast Medium,NaN,8.0,56.0,65.0,PBKS,PBKS,14.0,Capped,200

In [ ]:
df.shape

(574, 21)

In [ ]:
df.columns

Index(['List Sr.No.', 'Set No.', '2025 Set', 'First Name', 'Surname',
       'Country', 'State Association', 'DOB', 'Age', 'Specialism',
       'Batting Skills', 'Bowling Skills', 'Test caps', 'ODI caps', 'T20 caps',
       'IPL caps', 'Previous IPLTeam(s)', '2024 Team', '2024 IPL', 'C/U/A',
       'Reserve Price Rs Lakh'],
      dtype='object')

###Data Columns Description:
* List Sr.No. - Serial number of the player in the auction list.
* Set No. - Grouping of players into sets for auction purposes.
* 2025 Set - Specific set identifier for 2025 auction.
* First Name - Player's first name.
* Surname - Player's last name.
* Country - Nationality of the player.
* State Association - State or regional cricket association.
* DOB - Date of Birth of the player.
* Age - Player’s age as of 2025.
* Specialism - Player’s role (e.g., Batter, Bowler, All-Rounder, Wicketkeeper).
* Test Caps - Number of Test matches played by the player.
* ODI Caps - Number of One Day International matches played.
* T20 Caps - Number of T20 International matches played.
* IPL - Number of IPL matches played by the player.
* Previous IPL Team(s) - List of IPL teams the player has been associated with.
* 2024 Team - Player's team during the 2024 IPL season.
* 2024 IPL - Performance metrics or appearances in the 2024 season.
* C/U/A - Capped/Uncapped/Associate player status.
* Reserve Price Rs Lakh - Base price for the auction, in Indian Rupees (Lakh).

In [ ]:
df.isnull().sum()

List Sr.No.                0
Set No.                    0
2025 Set                   0
First Name                 0
Surname                    0
Country                    0
State Association        208
DOB                        0
Age                        0
Specialism                 0
Batting Skills             0
Bowling Skills            77
Test caps                438
ODI caps                 367
T20 caps                 355
IPL caps                 276
Previous IPLTeam(s)      277
2024 Team                375
2024 IPL                 375
C/U/A                      0
Reserve Price Rs Lakh      0
dtype: int64

In [ ]:
#data cleaning
df['State Association'] = df['State Association'].fillna('International')
df['Bowling Skills'] = df['Bowling Skills'].fillna('Can not bowl ')
df['Test caps'] = df['Test caps'].fillna(0)
df['ODI caps'] = df['ODI caps'].fillna(0)
df['T20 caps'] = df['T20 caps'].fillna(0)
df['IPL caps'] = df['IPL caps'].fillna(0)
df['Previous IPLTeam(s)'] = df['Previous IPLTeam(s)'].fillna('first time in IPL')
df['2024 Team'] = df['2024 Team'].fillna('do not play in 2024')
df['2024 IPL'] = df['2024 IPL'].fillna(0)

In [ ]:
df.isnull().sum()

List Sr.No.              0
Set No.                  0
2025 Set                 0
First Name               0
Surname                  0
Country                  0
State Association        0
DOB                      0
Age                      0
Specialism               0
Batting Skills           0
Bowling Skills           0
Test caps                0
ODI caps                 0
T20 caps                 0
IPL caps                 0
Previous IPLTeam(s)      0
2024 Team                0
2024 IPL                 0
C/U/A                    0
Reserve Price Rs Lakh    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   List Sr.No.            574 non-null    int64
 1   Set No.                574 non-null    int64
 2   2025 Set               574 non-null    object
 3   First Name             574 non-null    object
 4   Surname                574 non-null    object
 5   Country                574 non-null    object
 6   State Association      574 non-null    object
 7   DOB                    574 non-null    object
 8   Age                    574 non-null    int64
 9   Specialism             574 non-null    object
 10  Batting Skills         574 non-null    object
 11  Bowling Skills         574 non-null    object
 12  Test caps              574 non-null    float64
 13  ODI caps               574 non-null    float64
 14  T20 caps               574 non-null    float64
 15  IPL caps               574 non-null    float64
 16  Previous IPLTeam(s)    574 non-null    object
 17  2024 Team              574 non-null    object
 18  2024 IPL               574 non-null    float64
 19  C/U/A                  574 non-null    object
 20  Reserve Price Rs Lakh  574 non-null    int64
dtypes: float64(5), int64(4), object(12)
memory usage: 94.3+ KB

In [ ]:
df['full name'] = df['First Name'] + ' ' + df['Surname']

In [ ]:
col = df.pop('full name')
df.insert(df.columns.get_loc('Surname') + 1, 'full name', col)

In [ ]:
caps_cols = ['Test caps', 'ODI caps', 'T20 caps', 'IPL caps']
df[caps_cols] = df[caps_cols].astype('int64')
df['DOB'] = pd.to_datetime(df['DOB'], format='%d-%m-%Y')

In [ ]:
df.to_excel('TATA-IPL-2025-Auction-List-cleaned.xlsx', index=False)

In [ ]:
from google.colab import files

files.download('TATA-IPL-2025-Auction-List-cleaned.xlsx')